# Generated by Django 5.1.4 on 2026-06-18 06:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Malumot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mashina_raqami', models.CharField(max_length=16, unique=True)),
                ('joriy_hudud', models.CharField(choices=[('Toshkent', 'Toshkent'), ('Toshkent viloyati', 'Toshkent viloyati'), ('Andijon', 'Andijon'), ('Namangan', 'Namangan'), ('Fargona', 'Fargona'), ('Sirdaryo', 'Sirdaryo'), ('Jizzax', 'Jizzax'), ('Samarqand', 'Samarqand'), ('Qashqadaryo', 'Qashqadaryo'), ('Surxondaryo', 'Surxondaryo'), ('Buxoro', 'Buxoro'), ('Navoiy', 'Navoiy'), ('Xorazm', 'Xorazm'), ('Qoraqalpogiston', 'Qoraqalpogiston')], max_length=64)),
                ('joriy_lat', models.FloatField(blank=True, null=True)),
                ('joriy_lng', models.FloatField(blank=True, null=True)),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'malumotlar',
                'ordering': ['mashina_raqami'],
                'indexes': [models.Index(fields=['joriy_hudud'], name='malumotlar_joriy_h_053f08_idx'), models.Index(fields=['is_available'], name='malumotlar_is_avai_783787_idx')],
            },
        ),
        migrations.CreateModel(
            name='Zapros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yuk_ortish_joyi', models.CharField(choices=[('Toshkent', 'Toshkent'), ('Toshkent viloyati', 'Toshkent viloyati'), ('Andijon', 'Andijon'), ('Namangan', 'Namangan'), ('Fargona', 'Fargona'), ('Sirdaryo', 'Sirdaryo'), ('Jizzax', 'Jizzax'), ('Samarqand', 'Samarqand'), ('Qashqadaryo', 'Qashqadaryo'), ('Surxondaryo', 'Surxondaryo'), ('Buxoro', 'Buxoro'), ('Navoiy', 'Navoiy'), ('Xorazm', 'Xorazm'), ('Qoraqalpogiston', 'Qoraqalpogiston')], max_length=64)),
                ('yuk_ortish_lat', models.FloatField(blank=True, null=True)),
                ('yuk_ortish_lng', models.FloatField(blank=True, null=True)),
                ('yuk_tushirish_joyi', models.CharField(choices=[('Toshkent', 'Toshkent'), ('Toshkent viloyati', 'Toshkent viloyati'), ('Andijon', 'Andijon'), ('Namangan', 'Namangan'), ('Fargona', 'Fargona'), ('Sirdaryo', 'Sirdaryo'), ('Jizzax', 'Jizzax'), ('Samarqand', 'Samarqand'), ('Qashqadaryo', 'Qashqadaryo'), ('Surxondaryo', 'Surxondaryo'), ('Buxoro', 'Buxoro'), ('Navoiy', 'Navoiy'), ('Xorazm', 'Xorazm'), ('Qoraqalpogiston', 'Qoraqalpogiston')], max_length=64)),
                ('yuklash_sanasi', models.DateField()),
                ('status', models.CharField(choices=[('new', 'Yangi'), ('matched', 'Tavsiya berildi'), ('no_match', 'Mos mashina yoq')], default='new', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'zaproslar',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='zaproslar_status_9eb6e6_idx'), models.Index(fields=['yuk_ortish_joyi'], name='zaproslar_yuk_ort_e7c2d7_idx'), models.Index(fields=['created_at'], name='zaproslar_created_38f388_idx')],
            },
        ),
        migrations.CreateModel(
            name='AgentTaklif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reyting_ball', models.FloatField()),
                ('masofa_km', models.FloatField(blank=True, null=True)),
                ('agent_izohi', models.TextField(blank=True)),
                ('zapros_yaratilgan_vaqti', models.DateTimeField()),
                ('agent_taklif_bergan_vaqti', models.DateTimeField()),
                ('latency_ms', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mashina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='takliflar', to='matching.malumot')),
                ('zapros', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='takliflar', to='matching.zapros')),
            ],
            options={
                'db_table': 'agent_takliflari',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['zapros'], name='agent_takli_zapros__a2d9fb_idx'), models.Index(fields=['mashina'], name='agent_takli_mashina_73f6ec_idx'), models.Index(fields=['created_at'], name='agent_takli_created_5c9f0b_idx')],
            },
        ),
    ]
