# Generated by Django 5.1.4 on 2026-06-18 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenttaklif',
            name='feedback',
            field=models.CharField(choices=[('pending', 'Baholanmagan'), ('accepted', 'Qabul qilindi'), ('rejected', 'Rad etildi')], default='pending', max_length=16),
        ),
        migrations.AddField(
            model_name='agenttaklif',
            name='feedback_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='agenttaklif',
            index=models.Index(fields=['feedback'], name='agent_takli_feedbac_7e5ef1_idx'),
        ),
    ]
